### ISSUE TITLE
IMOS check_data_variables shouldn't look at coordinate vars

### ISSUE THREAD

**Issue by mhidas** [aodn/compliance-checker#2]
Running the IMOS checker on the file  [imos_good_data.nc](https://github.com/aodn/compliance-checker/blob/IMOS-Checker/compliance_checker/tests/data/imos_good_data.nc) used for the unittests gives the fail result:

```
var                                    :3:   164/167 :  
    data_variable                      :3:    29/32 :  
        LATITUDE                       :3:     3/ 4 :  
            check_dimension            :3:     0/ 1 : dimension doesn't contain
                                                      TIME, LATITUDE, LONGITUDE,
                                                      DEPTH
```

And similarly for variables `LONGITUDE` and `NOMINAL_DEPTH`.

This should not happen because these are all coordinate variables, not data variables (e.g. `TEMP:coordinates = "TIME LATITUDE LONGITUDE NOMINAL_DEPTH DEPTH"`).

**Comment by fxmzb123** [comment]
This has been fixed in new branch IMOS-Checker-Issue-2

**Comment by mhidas** [comment]
@fxmzb123 Thanks, but that's not quite fixed yet. My description of the issue above was not quite right. When finding data variables, we want to exclude not only coordinate and ancillary variables, but also _auxiliary coordinate variables_ ([definition](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html#terminology)). These variables are **not** coordinate variables (i.e. not same name as their single dimension) but are listed in any other variable's _coordinates_ attribute.

**Comment by mhidas** [comment]
@fxmzb123 I've added a unittest on your branch to show what I mean.

**Comment by fxmzb123** [comment]
this has been fixed and branch has been rebased.

**Comment by mhidas** [comment]
Looks good! Thanks Ming.
